steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/${SERVICE_NAME}:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${PROJECT_ID}/${SERVICE_NAME}:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - '${SERVICE_NAME}'
    - '--region=${REGION}'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=${SERVICE_ACCOUNT_EMAIL}'
    - '--image=gcr.io/${PROJECT_ID}/${SERVICE_NAME}:$SHORT_SHA'