--- 
images: 
  - gcr.io/$PROJECT_ID/tomcat
steps: 
  - 
    args: 
      - "-c"
      - "docker pull gcr.io/$PROJECT_ID/tomcat:latest || exit 0\n"
    entrypoint: bash
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - build
      - "-t"
      - gcr.io/$PROJECT_ID/tomcat
      - "--cache-from"
      - gcr.io/$PROJECT_ID/tomcat
      - "."
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - push
      - gcr.io/$PROJECT_ID/tomcat
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - beta
      - run
      - deploy
      - tomcat
      - "--image"
      - "gcr.io/$PROJECT_ID/tomcat:latest"
      - "--region"
      - europe-west1
      - "--platform"
      - managed
      - "--allow-unauthenticated"
    name: gcr.io/cloud-builders/gcloud
